apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-search-be
  labels:
    app: city-search-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-search-be
  template:
    metadata:
      labels:
        app: city-search-be
    spec:
      containers:
      - name: city-search-be
        image: lavanjv/city-search-be:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: city-search-be-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: city-search-be-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: city-search-be-secret
              key: DB_PASSWORD
        - name: CORS_URL
          valueFrom:
            secretKeyRef:
              name: city-search-be-secret
              key: CORS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: city-search-be-service
spec:
  selector:
    app: city-search-be
  ports:
  - protocol: TCP
    port: 6543
    targetPort: 8080
  type: NodePort
