apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-search-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: city-search-be
  template:
    metadata:
      labels:
        app: city-search-be
    spec:
      containers:
        - name: city-search-be
          image: lavanjv/city-search-be:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: city-search-be-service
spec:
  selector:
    app: city-search-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
